import { useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8011'
const Arrow = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M9 5h10v10" /></svg>
const domain = (url) => { try { return new URL(url).hostname.replace(/^www\./, '') } catch { return 'website' } }
const platform = (url) => ['instagram.com', 'facebook.com', 'x.com', 'twitter.com', 'tiktok.com', 'linkedin.com', 'youtube.com', 'pinterest.com', 'reddit.com'].find((item) => url?.includes(item))?.split('.')[0] || domain(url)
function HeroArt() { return <div className="hero-art" aria-hidden="true"><i className="orbit" /><i className="sphere" /><i className="card card-one"><b /><b /><b /></i><i className="card card-two"><b /></i><i className="ring" /><i className="dot dot-one" /><i className="dot dot-two" /></div> }
function Result({ result, onReview }) { const source = platform(result.url); return <article className="result-card"><div className="result-mark">{source[0]?.toUpperCase()}</div><div className="result-copy"><p>{source}</p><h3>{result.title || 'Matching social post'}</h3><span>{domain(result.url)} {result.face_score != null && `· ${(result.face_score * 100).toFixed(0)}% face score`}</span></div><button className="review-button" onClick={() => onReview(result)}>Verify <Arrow /></button></article> }

export default function App() {
  const [page, setPage] = useState('home'); const [imageUrl, setImageUrl] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [searchData, setSearchData] = useState(null); const [selected, setSelected] = useState(null); const [chainResult, setChainResult] = useState(null); const [chainLoading, setChainLoading] = useState(false)
  const rawUrl = imageUrl.trim(); const previewUrl = /^https?:\/\//i.test(rawUrl) ? rawUrl : `https://${rawUrl}`; const matches = searchData?.social_matches || []; const face = searchData?.face; const faceFingerprint = searchData?.face_phash || ''
  function go(next) { if (next === 'results' && !searchData) return setPage('search'); if (next === 'verify' && !selected) return setPage(searchData ? 'results' : 'search'); setPage(next) }
  function update(event) { setImageUrl(event.target.value); setSearchData(null); setSelected(null); setChainResult(null); setError(null) }
  async function search(event) { event.preventDefault(); if (!rawUrl) return; setLoading(true); setError(null); setSelected(null); setChainResult(null); try { const response = await fetch(`${API}/api/face/search`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ image_url: previewUrl, engine: 'both', amount: 20 }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || `Backend ${response.status}`); setSearchData(body); setPage('results') } catch (err) { setError(`Face search failed: ${err.message}`) } finally { setLoading(false) } }
  async function chainAction(action) { if (!selected) return; setChainLoading(true); setError(null); try { const response = await fetch(`${API}/api/evidence/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ post: selected, face_fingerprint: faceFingerprint }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail || `Blockchain ${response.status}`); setChainResult({ action, ...body }) } catch (err) { setError(`${action === 'register' ? 'Registration' : 'Verification'} failed: ${err.message}`) } finally { setChainLoading(false) } }
  return <main className="app-shell"><nav className="top-nav"><button className="brand" onClick={() => go('home')}>image<span>trace</span></button><div className="nav-steps">{[['search', '01', 'Search'], ['results', '02', 'Results'], ['verify', '03', 'Verify']].map(([key, number, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => go(key)}>{number} <span>{label}</span></button>)}</div></nav>
    {page === 'home' && <section className="home-screen"><div className="home-copy"><p className="eyebrow">FACE TRACEABILITY</p><h1>Find. prove.<br />verify.</h1><p className="lede">Find public posts that match a face scan, then create a tamper-evident proof on a local blockchain.</p><button className="primary-action" onClick={() => go('search')}>Start a search <Arrow /></button></div><HeroArt /><section className="feature-strip"><p>HOW IT WORKS</p><div>{[['01', 'Scan a face', 'Use a public image URL.'], ['02', 'Find social posts', 'Live reverse-image search.'], ['03', 'Verify evidence', 'Record its fingerprint on-chain.']].map(([n, title, text]) => <article key={n}><b>{n}</b><h2>{title}</h2><span>{text}</span></article>)}</div></section></section>}
    {page === 'search' && <section className="search-screen"><header><p className="eyebrow">01 / SEARCH</p><h1>Search by face.</h1><p>Paste a public image URL. We detect and encode the face before searching for matching social posts.</p></header><form className="search-stack" onSubmit={search}><div className="url-row"><input aria-label="Public face image URL" type="text" inputMode="url" value={imageUrl} onChange={update} placeholder="Paste a public face-image URL" autoComplete="url" /><button disabled={loading || !rawUrl}>{loading ? 'Scanning…' : <>Search <Arrow /></>}</button></div>{rawUrl && <div className="preview-wrap"><p>Face scan preview</p><img src={previewUrl} alt="Face image to search" /></div>}</form>{error && <p className="error">{error}</p>}</section>}
    {page === 'results' && <section className="results-screen"><header className="page-heading"><div><p className="eyebrow">02 / RESULTS</p><h1>Social matches.</h1></div><button className="text-action" onClick={() => go('search')}>New search <Arrow /></button></header><div className="scan-summary"><img src={searchData?.face_crop_dataurl || previewUrl} alt="Detected face crop" /><div><p>FACE SCAN</p><strong>{face?.face_found ? `${face.faces?.length || 1} face detected` : 'No face detected — image fingerprint used'}</strong><span>Fingerprint: {faceFingerprint || 'Unavailable'}</span></div></div><section className="result-grid">{matches.length ? matches.map((item, index) => <Result key={`${item.url}-${index}`} result={item} onReview={(result) => { setSelected(result); setPage('verify') }} />) : <p className="empty">No social-media matches were found. Try another public image URL.</p>}</section></section>}
    {page === 'verify' && <section className="verify-screen"><p className="eyebrow">03 / VERIFY</p><h1>Record evidence.</h1><p className="lede">Only a SHA-256 fingerprint of the selected post evidence is written to the local blockchain—not the post or face data.</p>{selected && <article className="verify-card"><img src={selected.thumbnail_url || searchData?.face_crop_dataurl || previewUrl} alt="Selected result" /><div><p className="match-label">SELECTED SOCIAL POST</p><h2>{selected.title || platform(selected.url)}</h2><span>{domain(selected.url)}</span><a href={selected.url} target="_blank" rel="noreferrer">Open source <Arrow /></a></div></article>}<div className="chain-actions"><button className="primary-action" disabled={chainLoading} onClick={() => chainAction('register')}>{chainLoading ? 'Working…' : 'Record on blockchain'} <Arrow /></button><button className="outline-action" disabled={chainLoading} onClick={() => chainAction('verify')}>Verify record</button></div>{chainResult && <section className={`chain-result ${chainResult.verified === false ? 'failed' : ''}`}><p>{chainResult.action === 'register' ? (chainResult.already_registered ? 'ALREADY RECORDED' : 'RECORDED ON LOCAL BLOCKCHAIN') : chainResult.verified ? 'VERIFIED — HASHES MATCH' : 'NOT VERIFIED — NO MATCHING RECORD'}</p><code>Hash: {chainResult.content_hash || chainResult.calculated_hash}</code>{chainResult.transaction_hash && <code>Transaction: {chainResult.transaction_hash}</code>}{chainResult.block_number != null && <span>Block #{chainResult.block_number} · Chain ID {chainResult.network}</span>}</section>}{error && <p className="error">{error}</p>}<button className="back-button" onClick={() => go('results')}>← Back to results</button></section>}
  </main>
}
