import { useMemo, useState } from 'react'
import './App.css'

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8011'
const RULES = [{ name: 'Instagram', domains: ['instagram.com'] }, { name: 'Facebook', domains: ['facebook.com', 'fb.com'] }, { name: 'X / Twitter', domains: ['x.com', 'twitter.com'] }, { name: 'YouTube', domains: ['youtube.com', 'youtu.be'] }, { name: 'TikTok', domains: ['tiktok.com'] }, { name: 'LinkedIn', domains: ['linkedin.com'] }, { name: 'Pinterest', domains: ['pinterest.com', 'pin.it'] }, { name: 'Reddit', domains: ['reddit.com'] }]
const Arrow = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M9 5h10v10" /></svg>
const domain = (url) => { try { return new URL(url).hostname.replace(/^www\./, '') } catch { return 'website' } }
const platform = (url) => RULES.find(({ domains }) => domains.some((item) => url?.toLowerCase().includes(item)))?.name

function HeroArt() { return <div className="hero-art" aria-hidden="true"><i className="orbit" /><i className="sphere" /><i className="card card-one"><b /><b /><b /></i><i className="card card-two"><b /></i><i className="ring" /><i className="dot dot-one" /><i className="dot dot-two" /></div> }
function Result({ result, onReview }) { const source = platform(result.url) || result.domain || domain(result.url); return <article className="result-card"><div className="result-mark">{source[0]}</div><div className="result-copy"><p>{source}</p><h3>{result.title || 'Matching page'}</h3><span>{domain(result.url)}</span></div><button className="review-button" onClick={() => onReview(result)}>Review <Arrow /></button></article> }

export default function App() {
  const [page, setPage] = useState('home'); const [imageUrl, setImageUrl] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [results, setResults] = useState(null); const [selected, setSelected] = useState(null)
  const rawUrl = imageUrl.trim(); const previewUrl = /^https?:\/\//i.test(rawUrl) ? rawUrl : `https://${rawUrl}`
  const allResults = useMemo(() => { if (!results) return []; const seen = new Set(); return [results.yandex?.info_pages, results.yandex?.similar_images, results.google?.matching_pages, results.google?.similar_images].flat().filter((item) => item?.url && !seen.has(item.url) && seen.add(item.url)) }, [results])
  function go(next) { if (next === 'results' && !results) return setPage('search'); if (next === 'verify' && !selected) return setPage(results ? 'results' : 'search'); setPage(next) }
  function update(event) { setImageUrl(event.target.value); setResults(null); setSelected(null); setError(null) }
  async function search(event) { event.preventDefault(); if (!rawUrl) return; setLoading(true); setError(null); try { const response = await fetch(`${API}/api/search`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ image_url: previewUrl, engine: 'both', amount: 30 }) }); if (!response.ok) throw new Error(`Backend ${response.status}`); setResults(await response.json()); setPage('results') } catch (err) { setError(`Search failed: ${err.message}. Is the backend running on ${API}?`) } finally { setLoading(false) } }
  function review(result) { setSelected(result); setPage('verify') }
  return <main className="app-shell"><nav className="top-nav"><button className="brand" onClick={() => go('home')}>image<span>trace</span></button><div className="nav-steps">{[['search', '01', 'Search'], ['results', '02', 'Results'], ['verify', '03', 'Verify']].map(([key, number, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => go(key)}>{number} <span>{label}</span></button>)}</div></nav>
    {page === 'home' && <section className="home-screen"><div className="home-copy"><p className="eyebrow">IMAGE INTELLIGENCE</p><h1>Find where<br />images travel.</h1><p className="lede">A focused reverse image search for discovering matching pages, social posts, and sources across the web.</p><button className="primary-action" onClick={() => go('search')}>Start a search <Arrow /></button></div><HeroArt /><section className="feature-strip"><p>HOW IT WORKS</p><div>{[['01', 'Paste a URL', 'Start with any public image.'], ['02', 'Explore matches', 'See where it appears.'], ['03', 'Review a source', 'Open the result you need.']].map(([n, title, text]) => <article key={n}><b>{n}</b><h2>{title}</h2><span>{text}</span></article>)}</div></section></section>}
    {page === 'search' && <section className="search-screen"><header><p className="eyebrow">01 / SEARCH</p><h1>Search by image.</h1><p>Paste a public image URL and we’ll look for matches across the web.</p></header><form className="search-stack" onSubmit={search}><div className="url-row"><input aria-label="Image URL" type="text" inputMode="url" value={imageUrl} onChange={update} placeholder="Paste image URL" autoComplete="url" /><button disabled={loading || !rawUrl}>{loading ? 'Searching…' : <>Search <Arrow /></>}</button></div>{rawUrl && <div className="preview-wrap"><p>Image preview</p><img src={previewUrl} alt="Image to search" /></div>}</form>{error && <p className="error">{error}</p>}</section>}
    {page === 'results' && <section className="results-screen"><header className="page-heading"><div><p className="eyebrow">02 / RESULTS</p><h1>Matches found.</h1></div><button className="text-action" onClick={() => go('search')}>New search <Arrow /></button></header><div className="source-row"><img src={previewUrl} alt="Searched image" /><div><p>YOUR IMAGE</p><span>{allResults.length} matching page{allResults.length === 1 ? '' : 's'} found</span></div></div><section className="result-grid">{allResults.length ? allResults.map((item, index) => <Result key={`${item.url}-${index}`} result={item} onReview={review} />) : <p className="empty">No matching pages were found for this image.</p>}</section></section>}
    {page === 'verify' && <section className="verify-screen"><p className="eyebrow">03 / VERIFY</p><h1>Review the match.</h1><p className="lede">Confirm the result and open the original page to review its context.</p>{selected && <article className="verify-card"><img src={previewUrl} alt="Searched image" /><div><p className="match-label">MATCHING SOURCE</p><h2>{selected.title || platform(selected.url) || domain(selected.url)}</h2><span>{domain(selected.url)}</span><a href={selected.url} target="_blank" rel="noreferrer">Open source <Arrow /></a></div></article>}<button className="back-button" onClick={() => go('results')}>← Back to results</button></section>}
  </main>
}
